"""
1. import modules
2. define function
3. define domain of characters
    ascii_letters = a to z and A to Z
    digits         = 0 to 9
    punctuation     = all special characters 

4. generate string of int digits 
    .join function is used to join all the characters which will be generated by random.choice function
    for loop is used so that random characters are generated x number of times
    and ''.join because '' indicates the string to be joined is empty at first instance. that means we always get a new string everytime we call the function.

5. save the result into variable / print it.. according to need.. 

"""

import string
import random

def generate_random_password(int):
    letters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(letters) for i in range(int))
    print(password)


generate_random_password(8) 

"""because 8 is the min characters req to create an account"""


"""

THANK YOU FOR WATCHING!!!


"""
